const obj = {
  BUCKET_NAME: '',
  AWS_REGION: '',
  COGNITO_IDENTITY_POOL_ID: '',
  COGNITO_USER_POOL_ID: '',
  COGNITO_CLIENT_ID: ''
};

export const {
  AWS_REGION,
  BUCKET_NAME,
  COGNITO_IDENTITY_POOL_ID,
  COGNITO_USER_POOL_ID,
  COGNITO_CLIENT_ID
} = obj;
